### ISSUE TITLE
failed to enter wifi client mode

### ISSUE THREAD

**Issue by jgw365** [DroneBridge/ESP32#52] opened 2023-12-07 07:15 UTC
when I try to enter a id or password consists of numbers（such as id:629,password:1234567890),something goes wrong. dronebridge can't save messgaes into esp32 by the website

**Comment by jgw365** [comment] 2023-12-07 07:20
seen on the monitor :Guru Meditation Error: Core  1 panic'ed (LoadProhibited). Exception was unhandled.

**Comment by seeul8er** [comment] 2023-12-27 23:57
Thank you for the bug report. The issue is fixed with the new v1.3 release!

**Closed by seeul8er** 2023-12-27 23:57 UTC
